### ISSUE TITLE
Location Argument does not work in Alfred 3

### ISSUE THREAD

**Issue by mikedvzo** [jason0x43/jc-weather#10]
Workflow still functions but it does not accept location argument any longer.

**Comment by jeffbyrnes** [comment]
It works well for me, @mikedvzo, using the current version of Alfred 3.

**Comment by jason0x43** [comment]
Please note that this workflow is no longer maintained. A new version of the workflow with full support for Alfred 3 is available [here](https://github.com/jason0x43/alfred-weather).
