### ISSUE TITLE
Error "You need to set your weather service" prohibits setting weather service

### ISSUE THREAD

**Issue by brandonjp** [jason0x43/jc-weather#9]
When no weather service is set, the error message "You need to set your weather service" dialog opens anytime the 'weather' keyword is issued in Alfred.  

If Alfred History is set to "Show latest history if within 5 minutes" (Alfred Preferences > Advanced > History), this makes it nearly impossible to set the weather service for average users.  

Definitely an issue that can be worked around by restarting Alfred or waiting 5 minutes (or really fast typing if you're quick enough), but it becomes quite frustrating.

**Comment by jason0x43** [comment]
Please note that this workflow is no longer maintained. A new version of the workflow with an improved setup process is available [here](https://github.com/jason0x43/alfred-weather).
